language: c

sudo: required

services:
  - docker

branches:
  only:
    - master
    - develop
    - feature/COR-538

before_install:
  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

script:
  - ./scripts/build.rb
 
deploy:
  provider: script
  script: ./scripts/deploy.rb
  skip_cleanup: true
  on:
    condition: $TRAVIS_PULL_REQUEST = false
    branch: master

notifications:
  hipchat: i5cATjdAiZ9LKkshPi3FF1UsWc27ggKyhoRDmPy9:non-critical-notifications
  email:
    recipients:
      - sergey.semichev@sentrana.com
    on_success: change
    on_failure: always