---

  - name: Install base packages
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ common_default_packages }}"


  - name: Remove packages
    yum:
      name: "{{ item }}"
      state: absent
    with_items: "{{ common_removed_packages }}"
