---

  - name: Install base packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ common_default_packages }}"
    
  - name: Install pip based packages
    command: pip install -U "{{ item }}"
    with_items: "{{ common_pip_packages }}"
