---

  - import_tasks: install.yml
    tags: common_install
  - import_tasks: config.yml
    tags: common_config
  - import_tasks: ansible-message.yml
    tags: common_motd
  - import_tasks: environment.yml
    tags: common_environment
  - import_tasks: disk.yml
    tags: common_disk
  - name: Add ntpd cron on restart
    shell: (crontab -l ; echo "@reboot ( sleep 90; /sbin/service ntpd restart )") | crontab -
