export RMQ_DOCKER_IMAGE_VERSION="v1.0"
export USER=${RABBIT_USERNAME}
export PASSWORD=${RABBIT_PASSWORD}
export SRV_INSTANCES=${RMQ_SRV_INSTANCES}
export SRV_CPUS=${RMQ_SRV_CPUS}
export SRV_MEM=${RMQ_SRV_MEM}