CONFIG=deepcortex-settings
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
CUSTOMER_KEY=391d14f4-2eec-a099-e53a-d4263afba016
DCOS_USERNAME=
DCOS_PASSWORD=
DOCKER_REGISTRY_AUTH_TOKEN='ZGVlcGNvcnRleHJlYWQ6bnkyUDJwUlVMWHcyY1Vydg=='
DOCKER_EMAIL_LOGIN='dcos-readonly@deepcortex.ai'