---
- hosts: all
  become: yes
  pre_tasks:
    - name: gather ec2 facts
      action: ec2_metadata_facts
      tags:
        - always
  vars:
    filebeat_config_registry_file: /var/lib/filebeat/registry
    filebeat_config_prospectors: |
      filebeat:
        prospectors:
          -
            input_type: log
            paths:
              - /var/lib/mesos/slave/slaves/*/frameworks/*/executors/*/runs/latest/stdout
              - /var/lib/mesos/slave/slaves/*/frameworks/*/executors/*/runs/latest/stderr
            document_type: "frameworks"
            registry_file: "{{filebeat_config_registry_file}}_frameworks"
            exclude_lines: ["DEBUG"]
            tail_files: true
          -
            input_type: log
            paths:
              - /var/log/mesos/*.log
            document_type: "mesos"
            registry_file: "{{filebeat_config_registry_file}}_mesos"
            exclude_lines: ["DEBUG"]
            tail_files: true
          -
            input_type: log
            paths:
              - /var/log/dcos/dcos.log
            document_type: "dcos"
            registry_file: "{{filebeat_config_registry_file}}_dcos"
            exclude_lines: ["DEBUG"]
            tail_files: true
    filebeat_config_output: |
      output:
        elasticsearch:
          hosts: [ "coordinator.elastic.l4lb.thisdcos.directory:9200" ]
    filebeat_config_shipper: |
      shipper:
    filebeat_config_logging: |
      logging:
        files:
          rotateeverybytes: 10485760 # = 10MB
    filebeat_config: |
      {{filebeat_config_prospectors}}
      {{filebeat_config_output}}
      {{filebeat_config_shipper}}
      {{filebeat_config_logging}}
  roles:
    - common
    - docker
    - filebeat

- hosts: bootstrap
  become: yes
  vars:
    security: disabled
    registry: true
    superuser_username: deepcortex
    enterprise_dcos: true
    resolvers:
      - provider_dns_via_user_data
      - 8.8.4.4
      - 8.8.8.8
  roles:
    - bootstrap

- hosts: master
  become: yes

- hosts: slave
  become: yes
