---
- hosts: all
  become: yes
  pre_tasks:
    - name: gather ec2 facts
      action: ec2_metadata_facts
      tags:
        - always
  roles:
    - common
    - docker

- hosts: bootstrap
  become: yes
  vars:
    resolvers:
      - provider_dns_via_user_data
      - 8.8.4.4
      - 8.8.8.8
  roles:
    - bootstrap

- hosts: master
  become: yes

- hosts: slave
  become: yes
