---
- hosts: all
  become: yes
  pre_tasks:
    - name: gather ec2 facts
      action: ec2_metadata_facts
      tags:
        - always
  roles:
    - common
    - docker

- hosts: bootstrap
  become: yes
  roles:
    - bootstrap

- hosts: master
  become: yes

- hosts: slave
  become: yes
