---

# Only needed if we want to run docker containers on captain
# Needs to be fixed.
# - name: Login to dockerhub
#   docker_login:
#     registry: index.docker.io/v1/
#     email: "{{ email }}"
#     username: "{{ docker_login_username }}"
#     password: "{{ docker_registry_auth_token }}"

- name: Install percona-mongo
  yum:
    name: "https://{{ s3_endpoint }}/{{ artifacts_s3_bucket }}/packages/newrpm/Percona-Server-MongoDB-34-shell-3.4.14-2.12.el7.x86_64.rpm"
    state: present

- name: Download dcos cli
  get_url:
    url: "https://{{ s3_endpoint }}/{{ artifacts_s3_bucket }}/packages/artifacts/dcos"
    dest: /usr/local/bin/dcos
    mode: 0755

- name: Symlink /usr/local/bin/dcos to /usr/bin/dcos
  file:
    src: /usr/local/bin/dcos
    dest: /usr/bin/dcos
    state: link

- name: Copy services configuration files
  copy:
   dest: /opt/
   src: dcos_services
   owner: root
   group: root
   mode: 0644

- name: Copy tools files
  copy:
   dest: /opt/
   src: tools
   owner: root
   group: root
   mode: 0644

- name: Generate /etc/environment file
  template:
    src: etc/environment.j2
    dest: /etc/environment
    mode: 0644

- name: Install services
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
    - captain

- name: Enable services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - captain
