---
- name: Install ansible dependencies for docker_login
  pip:
    name: docker-py

- name: Start docker
  service:
    name: docker
    state: started

# - name: Login to dockerhub
#   docker_login:
#     registry: index.docker.io
#     email: "{{ email }}"
#     username: "{{ docker_login_username }}"
#     password: "{{ docker_registry_auth_token }}"

- name: Download dcos cli
  get_url:
    url: https://downloads.dcos.io/binaries/cli/linux/x86-64/dcos-1.10/dcos
    dest: /usr/local/bin/dcos
    mode: 0755

- name: Create a unique passwords
  shell: head /dev/urandom | tr -dc A-Za-z0-9 | head -c 17
  register: pwd
  with_items:
    - rabbit_password
    - aries_http_search_user_password
    - aries_http_command_user_password
    - cortex_http_search_user_password
    - http_search_user_password

- name: Populate passwords
  set_fact:
    passwords: "{{ passwords|default({}) | combine( {item.item: item.stdout} ) }}"
  with_items: "{{ pwd.results }}"

- name: Generate /etc/environment file
  template:
    src: etc/environment.j2
    dest: /etc/environment
    mode: 0644

- name: Print password
  debug:
    var: passwords

- name: Print passwords
  debug:
    msg: "Value of {{ item }}: {{ passwords[item] }}"
  with_items:
    - rabbit_password
    - aries_http_search_user_password
    - aries_http_command_user_password
    - cortex_http_search_user_password
    - http_search_user_password
