---

# Only needed if we want to run docker containers on captain
# Needs to be fixed.
# - name: Login to dockerhub
#   docker_login:
#     registry: index.docker.io/v1/
#     email: "{{ email }}"
#     username: "{{ docker_login_username }}"
#     password: "{{ docker_registry_auth_token }}"

- name: Download dcos cli
  get_url:
    url: https://downloads.dcos.io/binaries/cli/linux/x86-64/dcos-1.10/dcos
    dest: /usr/local/bin/dcos
    mode: 0755

- name: Symlink /usr/local/bin/dcos to /usr/bin/dcos
  file:
    src: /usr/local/bin/dcos
    dest: /usr/bin/dcos
    state: link

- name: Copy services configuration files
  copy:
   dest: /opt/
   src: dcos_services
   owner: root
   group: root
   mode: 0644

- name: Copy tools files
  copy:
   dest: /opt/
   src: tools
   owner: root
   group: root
   mode: 0644

- name: Check wheter endpoints file exists
  local_action: stat path={{ role_path }}/files/extra_files/endpoints.json
  register: endpoints

- name: Copy endpoints file if it exists
  copy: src=files/extra_files/endpoints.json dest=/usr/lib/python2.7/site-packages/botocore/data/
  when: endpoints.stat.exists

- name: Generate /etc/environment file
  template:
    src: etc/environment.j2
    dest: /etc/environment
    mode: 0644

- name: Install services
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
    - captain

- name: Enable services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - captain
