---
# Docker
email: support@deepcortex.ai
docker_login_username: deepcortex

# Common
dcos_username: "user"
dcos_password: "pass"
rabbit_hosts: "rabbitmq.marathon.l4lb.thisdcos.directory"
rabbit_user: "rabbit_user"
elastic_host: "coordinator.elastic.l4lb.thisdcos.directory"
elastic_port: 9200
elastic_ssl: 'false'

# Aries
aries_http_search_user_name: "aries-search-user"
aries_http_command_user_name: "aries-command-user"
aries_srv_instances: 3
aries_srv_cpus: 1
aries_srv_mem: 1024
aries_host: "aries-api-rest.marathon.l4lb.thisdcos.directory"
aries_port: 9000
aries_rest_url: "http://aries-api-rest.marathon.l4lb.thisdcos.directory:9000"
aries_elastic_job_index: "cortex_jobs_dev"
aries_elastic_heartbeat_index: "cortex_job_heartbeats_dev"

# Argo
argo_http_auth_user_name: "argo-auth-user"
argo_elastic_config_setting_index: "cortex_config_settings_dev"
argo_srv_instances: 3
argo_srv_cpus: 1
argo_srv_mem: 1024
argo_host: "argo-api-rest.marathon.l4lb.thisdcos.directory"
argo_port: 9000
argo_rest_url: "http://argo-api-rest.marathon.l4lb.thisdcos.directory:9000"

# Baile
baile_srv_instances: 1
baile_srv_cpus: 1
baile_srv_mem: 4096
baile_address: "baile.marathon.l4lb.thisdcos.directory:9000"
baile_rest_url: "http://baile.marathon.l4lb.thisdcos.directory:9000"
online_prediction_username: "online-predictor"
baile_aries_rest_version: "v1"
baile_cortex_rest_version: "v1"
baile_argo_rest_version: "v1"

# Baile Haproxy
baile_haproxy_srv_instances: 1
baile_haproxy_srv_cpus: 0.1
baile_haproxy_srv_mem: 65
baile_haproxy_rest_url: "http://baile-haproxy.marathon.l4lb.thisdcos.directory"

# Cortex
cortex_http_search_user_name: "cortex-search-user"
cortex_aries_rest_version: "v1"
cortex_srv_instances: 3
cortex_srv_cpus: 1
cortex_srv_mem: 1024
cortex_host: "cortex-api-rest.marathon.l4lb.thisdcos.directory"
cortex_port: 9000
cortex_rest_url: "http://cortex-api-rest.marathon.l4lb.thisdcos.directory:9000"

# Logstash
logstash_srv_instances: 1
logstash_srv_cpus: 0.1
logstash_srv_mem: 1024

# Orion
orion_http_search_user_name: "orion-search-user"
job_master_start_timeout: "5minutes"
job_master_heartbeat_timeout: "5minutes"
job_master_mesos_master_address: "master.mesos:5050"
job_master_cpus: 1
job_master_memory: 1024
job_master_instances: 1
orion_srv_instances: 3
orion_srv_cpus: 1
orion_srv_mem: 1024

# Pegasus
pegasus_http_auth_user_name: "pegasus-user"
pegasus_srv_instances: 3
pegasus_srv_cpus: 1
pegasus_srv_mem: 1024

# RabbitMQ
rmq_srv_instances: 3
rmq_srv_cpus: 0.1
rmq_srv_mem: 512

# Taurus
taurus_cortex_rest_version: "v1"
taurus_baile_rest_version: "v1.4"
taurus_aries_rest_version: "v1"
taurus_argo_rest_version: "v1"
taurus_srv_instances: 1
taurus_srv_cpus: 1
taurus_srv_mem: 1024
akka_persistence_journal_path: "/tmp/akka-persistence-journal"

# UM Service
um_mongodb_uri: "mongodb://mongodb.mongodb-replicaset.l4lb.thisdcos.directory:27017/um-service?replicaSet=rs"
um_service_url: "http://um-service.marathon.l4lb.thisdcos.directory"
email_on: 'false'
um_srv_instances: 1
um_srv_cpus: 1
um_srv_mem: 1024
